# src/test_generator.py
import os
import re
from jinja2 import Environment, FileSystemLoader, TemplateNotFound
from typing import List, Dict, Any, Optional

from .state import AuditState
from .scenarios import SCENARIOS # 정의된 시나리오 가져오기

# Jinja2 환경 설정 (템플릿 파일이 있는 디렉토리 지정)
template_dir = os.path.join(os.path.dirname(__file__), '../templates') # templates 폴더 가정
if not os.path.exists(template_dir):
    os.makedirs(template_dir)
    print(f"템플릿 디렉토리 생성: {template_dir}")
    # 기본 템플릿 파일 생성 (예시)
    default_template_content = """
// SPDX-License-Identifier: UNLICENSED
// Generated by Audit Agent for Scenario: {{ scenario.id }}
pragma solidity {{ compiler_version | default('^0.8.24') }};

import "forge-std/Test.sol";
{%- if scenario.required_imports %}
// Scenario-specific imports:
{% for imp in scenario.required_imports %}{{ imp }}
{% endfor %}
{%- endif %}

contract {{ test_contract_name }} is Test {

    // --- State Variables ---
    // Target contract instance (filled by generator)
    // {{ target_contract_declaration }} // 예: TargetContract internal targetContract;

    // Mock contract instances (filled by generator)
    /*
    {% if scenario.mock_deployments_code -%}
    {{ scenario.mock_deployments_code | indent(4) }}
    {%- endif %}
    */

    // --- Setup ---
    function setUp() public {
        // General setup logic (filled by generator)
        /*
        {% if scenario.setup_code -%}
        {{ scenario.setup_code | indent(8) }}
        {%- else -%}
        // Default setup: Deploy target contract?
        // targetContract = new TargetContract();
        {%- endif %}
        */
         // Placeholder: Deploy target contract if needed
         // targetContract = new {{ target_contract_name | default("TargetContract") }}(); // 기본값 추가
         console.log("Executing setUp for {{ test_contract_name }}");
    }

    // --- Test Function ---
    // MCP Test for Scenario: {{ scenario.id }} - {{ scenario.category }}
    // Description: {{ scenario.description }}
    function test_{{ scenario_id_snake_case }}() public {
        console.log("Scenario: {{ scenario.id }} - Precondition: {{ scenario.precondition }}");

        // --- Test Specific Setup ---
        /*
        {% if scenario.test_setup_code -%}
        {{ scenario.test_setup_code | indent(8) }}
        {%- else -%}
        // No specific test setup provided for this scenario.
        {%- endif %}
        */
        // Placeholder for scenario specific setup
        console.log("Applying test-specific setup for {{ scenario.id }}...");


        // --- Execution & Assertion ---
        console.log("Action: {{ scenario.action }}"); // 설명용
        console.log("Expected: {{ scenario.expected }}"); // 설명용

        {% if scenario.expected_revert_selector -%}
        // Expect Revert
        vm.expectRevert({{ scenario.expected_revert_selector }});
        {% endif -%}

        // Execute the action (filled by generator)
        /*
        {% if scenario.action_code -%}
        {{ scenario.action_code | indent(8) }}
        {%- else -%}
        // Placeholder: Execute the action described in scenario.action
        // Example: {{ target_contract_instance_name | default('targetContract') }}.{{ scenario.action_function | default('someAction') }}(...);
        {%- endif %}
        */
         // Placeholder for action execution
         console.log("Executing action for {{ scenario.id }}...");
         // Example: Replace with actual action code based on scenario
         // {{ target_contract_instance_name | default('targetContract') }}.someAction();

        {% if not scenario.expected_revert_selector and scenario.assertion_code -%}
        // Assert State Changes (filled by generator)
        {{ scenario.assertion_code | indent(8) }}
        {%- elif not scenario.expected_revert_selector -%}
        // Default assertion if no specific assertion code is provided and no revert is expected
        assertTrue(true, "Execution completed without revert (no specific assertions)");
        {%- endif %}
    }
}
"""
    try:
        # 기본 범용 템플릿 생성
        base_template_path = os.path.join(template_dir, "forge_test_base.t.sol.j2")
        if not os.path.exists(base_template_path):
             with open(base_template_path, "w") as f:
                 f.write(default_template_content)
             print("기본 템플릿 파일 'forge_test_base.t.sol.j2' 생성됨.")

    except OSError as e:
        print(f"템플릿 디렉토리 또는 파일 생성 오류: {e}")

try:
    env = Environment(loader=FileSystemLoader(template_dir), trim_blocks=True, lstrip_blocks=True)
except Exception as e:
    print(f"Jinja2 환경 로드 오류: {e}. 템플릿 디렉토리 확인 필요: {template_dir}")
    env = None # 환경 로드 실패 시 None으로 설정

def _to_snake_case(name: str) -> str:
    """문자열을 스네이크 케이스로 변환 (테스트 함수명 생성용)"""
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    s2 = re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()
    # ID에 포함될 수 있는 특수문자 제거 또는 대체
    s3 = re.sub(r'[^a-z0-9_]+', '_', s2)
    return s3.strip('_')

def _generate_test_contract_name(scenario_id: str) -> str:
    """시나리오 ID를 기반으로 유효한 Solidity 컨트랙트 이름을 생성합니다."""
    base_name = f"MCPTest_{scenario_id.replace('-', '_').replace('.', '_')}"
    # 숫자로 시작하거나 유효하지 않은 문자가 포함되지 않도록 처리
    valid_name = re.sub(r'^[^a-zA-Z_]+', '_', base_name)
    valid_name = re.sub(r'[^a-zA-Z0-9_]', '_', valid_name)
    return valid_name

def generate_mcp_tests(state: AuditState) -> Dict[str, Optional[List[str]] | Optional[str]]:
    """정의된 시나리오를 바탕으로 Forge 테스트 파일을 생성합니다."""
    print("--- MCP 테스트 코드 생성 시작 ---")
    repo_path = state.get("local_repo_path")
    repo_analysis = state.get("repo_analysis") # 컴파일러 버전 등 가져오기 위해 추가

    if not repo_path:
        return {"error": "Local repository path not found for test generation."}
    if not env:
         return {"error": "Jinja2 template environment not initialized."}

    # 상태에서 시나리오 목록 가져오기 (없으면 기본 SCENARIOS 사용)
    scenarios_to_run = state.get("mcp_scenarios", SCENARIOS)
    if not scenarios_to_run:
         print("  ! 검증할 시나리오가 없습니다.")
         return {"generated_test_files": []} # 빈 목록 반환

    test_dir = os.path.join(repo_path, "test", "mcp_generated") # 생성된 테스트 저장 경로
    if not os.path.exists(test_dir):
        os.makedirs(test_dir)
        print(f"  > MCP 테스트 디렉토리 생성: {test_dir}")

    generated_files: List[str] = []
    generation_errors: List[str] = []

    # repo_analysis에서 컴파일러 버전 정보 추출
    if not repo_analysis or not repo_analysis.get("compiler_versions"):
        return {"error": "컴파일러 버전 정보를 찾을 수 없습니다. 리포지토리 분석이 필요합니다."}
    
    compiler_version = repo_analysis["compiler_versions"][0]
    # 컴파일러 버전 문자열 정리 (예: 'solc-0.8.24' -> '^0.8.24')
    if compiler_version.startswith('solc-'):
        compiler_version = '^' + compiler_version.split('-')[1]

    for scenario in scenarios_to_run:
        scenario_id = scenario['id']
        # 이제 기본 템플릿만 사용
        template_name = scenario.get('template', 'forge_test_base.t.sol.j2')
        test_contract_name = _generate_test_contract_name(scenario_id)
        scenario_id_snake_case = _to_snake_case(scenario_id)
        output_filename = f"{test_contract_name}.t.sol"
        output_path = os.path.join(test_dir, output_filename)

        print(f"  > 시나리오 '{scenario_id}' 테스트 생성 중 (템플릿: {template_name})...")
        try:
            template = env.get_template(template_name)
            # 템플릿 렌더링에 필요한 모든 컨텍스트 변수 전달
            context = {
                "scenario": scenario,
                "test_contract_name": test_contract_name,
                "scenario_id_snake_case": scenario_id_snake_case,
                "compiler_version": compiler_version,
                # scenarios.py 에서 정의된 상세 필드들 전달
                "target_contract_name": scenario.get("target_contract_name", "TargetContract"), # 기본값 설정
                "target_contract_declaration": scenario.get("target_contract_declaration", "// Target contract declaration missing"),
                "target_contract_instance_name": scenario.get("target_contract_instance_name", "targetContract"),
                "required_imports": scenario.get("required_imports", []),
                "setup_code": scenario.get("setup_code", "// Default setup code missing"),
                "test_setup_code": scenario.get("test_setup_code", "// Test specific setup code missing"),
                "action_function": scenario.get("action_function"), # None일 수 있음
                "action_code": scenario.get("action_code", "// Action code missing"),
                "expected_revert_selector": scenario.get("expected_revert_selector"), # None일 수 있음
                "assertion_code": scenario.get("assertion_code", "assertTrue(true, 'Default assertion');") # 기본값
            }
            rendered_code = template.render(context)

            with open(output_path, "w", encoding="utf-8") as f:
                f.write(rendered_code)
            generated_files.append(output_path)
            print(f"    - 테스트 파일 생성 완료: {output_path}")

        except TemplateNotFound:
            err = f"템플릿 '{template_name}'을(를) 찾을 수 없습니다 ({scenario_id})."
            print(f"    ! 오류: {err}")
            generation_errors.append(err)
        except Exception as e:
            err = f"시나리오 '{scenario_id}' 테스트 생성 중 오류: {e}"
            print(f"    ! 오류: {err}")
            generation_errors.append(err)
            # traceback.print_exc() # 디버깅 시 주석 해제

    print(f"--- MCP 테스트 코드 생성 완료 (성공: {len(generated_files)}, 실패: {len(generation_errors)}) ---")

    error_msg = "; ".join(generation_errors) if generation_errors else None
    # 생성된 파일 목록과 에러 상태 반환
    return {"generated_test_files": generated_files, "error": error_msg}
